--- #YAML:1.0
name:               Mojo-Server-FCGI
version:            0.13
abstract:           ~
author:
    - Sebastian Riedel <sri@cpan.org>
license:            perl
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    FCGI:  0.67
    Mojo:  0.991242
resources:
    homepage:     http://mojolicious.org
    license:      http://dev.perl.org/licenses/
    MailingList:  http://lists.kraih.com/cgi-bin/mailman/listinfo
    repository:   http://github.com/kraih/mojo/tree/master
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
