--- #YAML:1.0
name:                Mojo-Server-FCGI
version:             0.06
abstract:            ~
license:             perl
author:              
    - Sebastian Riedel <sri@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    FCGI:                          0.67
    Mojo:                          0.991235
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
