--- #YAML:1.0
name:               Mojo-Server-FCGI
version:            0.27
abstract:           Speedy FastCGI implementation
author:
    - Sebastian Riedel <sri@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Carp:                 0
    ExtUtils::MakeMaker:  0
    FCGI:                 0.67
    File::Spec:           0
    File::Temp:           0
    FindBin:              0
    Getopt::Long:         0
    Mojolicious:          0.999922
    perl:                 5.008001
    Test::More:           0
resources:
    homepage:     http://mojolicious.org
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/mojolicious
    repository:   http://github.com/kraih/mojo
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
